---
title: "sbac_sankey"
author: "Cormac Harkins"
date: "December 29, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
# Data Prep:
# Use this file to prepare the Caliber 2015-16 ASG data visualizations
#   0 - LOAD all data frames that are needed to transform data
#
# Three main data tasks are accomplished in this file
#
#   1 - MELT data from CSV into a usable R format (prefix "melt")
#   2 - GENERATE base data frames for any graphical rollup (prefix "gen")
#   3 - ROLLUP data for graphs (prefix "roll")

setwd("/Users/cormac/shinydashboard-map-data")

####  LOAD ####
library(reshape2) # Not sure if I still need
library(plyr)
library(tidyverse) # Mainly dplyr, tidyr, ggplot2

fall_winter_2015_16 <- read_csv("f_w_asg_2015-16.csv",
                                col_types = cols(ClassName = col_character(),
                                                 StudentGrade = col_character()
                                                 )
                                )

winter_spring_2015_16 <- read_csv("w_s_asg_2015-16.csv",
                                  col_types = cols(ClassName = col_character(),
                                                   StudentGrade = col_character()
                                                   )
                                  )

spring_spring_2015_16 <- read_csv("s_s_asg_2015-16.csv",
                                  col_types = cols(ClassName = col_character(),
                                                   StudentGrade = col_character()
                                  )
)

setwd("/Users/cormac/shinydashboard-map") # Development

sbac_cut_scores <- readRDS("www/sbac_cut_scores.Rda")      # SBAC cut scores
status_norms <- readRDS("www/status_norms.Rda")         # NWEA Percentile Norms
growth_norms <- readRDS("www/growth_norms.Rda")         # NWEA Growth Norms
multipliers <- readRDS("www/multipliers.Rda")           # KIPP Foundation Tiered Target Multipliers
caliber_multipliers <- read_csv("www/caliber_multipliers.csv") # Caliber Targets

#### MELT ####

# Combine the data sets together
# Separate the term into season and year
# Create and keep variables with clearer names
# Join with the NWEA MAP growth norms
# Join with the NWEA MAP SBAC cut scores (adapted from Rui)

combo_map <- bind_rows(fall_winter_2015_16, winter_spring_2015_16) %>%
  bind_rows(spring_spring_2015_16) %>%
  separate(TermTested, into = c("Season", "Year"), sep = " ") %>%
  transmute(Season = Season,
            Year = Year,
            RIT = StartRIT,
            Subject = Subject,
            School = as.character(SchoolName),
            Grade = as.integer(revalue(as.character(StudentGrade), c('K' = '0'))),
            ID = StudentID,
            First = StudentFirstName,
            Last = StudentLastName) %>%
  distinct() %>%
  filter(Subject != "Language Usage") %>%
  left_join(y = status_norms, by = c("Grade","Subject","RIT","Season")) %>%
  left_join( y = sbac_cut_scores, by = c("Grade","Subject","RIT","Season")) %>%
  mutate(Quartile = ceiling(NPR/25)) %>%
  group_by(Grade, Subject, Season) %>%
  mutate(n_tested = sum(n())) %>%
  filter(n_tested >= 15)

####  GENERATE  ####

# Generate a Fall to Winter Growth data frame
# Filter Season == Fall or Winter
# Spread data into a start RIT and end RIT based on season
# Join with growth norms to add the typical growth goal
# Join with the caliber multiplier to add the the target growth goal
# Calculate the actual growth
# Calculate whether the typical growth and target growth goals were met
# Drop cases missing either a Fall or Winter test score
# Only keep cases in grades that have 15 or more students with valid scores

F_to_W_growth <- combo_map %>%
  filter(Season == "Fall" | Season == "Winter") %>%
  unite(temp, 4:9, sep = "/") %>%
  unite(scores, c(RIT, NPR, SBAC, Quartile), sep = "/") %>%
  select(-Year, -n_tested) %>%
  spread(key = Season, value = scores) %>%
  separate(Fall, c("Start_RIT", "Start_NPR", "Start_SBAC", "Start_Quartile"), sep = "/") %>%
  separate(Winter, c("End_RIT", "End_NPR", "End_SBAC", "End_Quartile"), sep = "/") %>%
  separate(temp, c("Subject", "School", "Grade", "ID", "First", "Last"), sep = "/") %>%
  mutate_each(funs(as.numeric), vars = c(-Subject, -School, - First, -Last)) %>%
  left_join(y = growth_norms %>%
              filter(Start_Season == "Fall" & End_Season == "Winter") %>%
              select(Subject, Grade, RIT, Growth_Goal),
            by = c("Subject","Grade","Start_RIT" = "RIT")) %>%
  left_join( y = caliber_multipliers, by = "Start_SBAC") %>%
  mutate(Growth_Season = "Fall-to-Winter",
         Actual_Growth = End_RIT - Start_RIT,
         Typical_Growth = Growth_Goal,
         Target_Growth = Growth_Goal*multiplier,
         Met_Typical = ifelse( Actual_Growth >= Typical_Growth,1,0),
         Met_Target = ifelse( Actual_Growth >= Target_Growth,1,0),
         Typ_not_Target = ifelse(Met_Typical == 1 & Met_Target == 0, 1, 0)
         ) %>%
  drop_na() %>%
  group_by(Grade, Subject) %>%
  mutate(n_tested = sum(n())) %>%
  filter(n_tested >= 15)

# Generate a Winter to Spring Growth data frame
# Same as above but filter Season == Winter or Spring

W_to_S_growth <- combo_map %>%
  filter(Season == "Winter" | Season == "Spring") %>%
  unite(temp, 4:9, sep = "/") %>%
  unite(scores, c(RIT, NPR, SBAC, Quartile), sep = "/") %>%
  select(-Year, -n_tested) %>%
  spread(key = Season, value = scores) %>%
  separate(Winter, c("Start_RIT", "Start_NPR", "Start_SBAC", "Start_Quartile"), sep = "/") %>%
  separate(Spring, c("End_RIT", "End_NPR", "End_SBAC", "End_Quartile"), sep = "/") %>%
  separate(temp, c("Subject", "School", "Grade", "ID", "First", "Last"), sep = "/") %>%
  mutate_each(funs(as.numeric), vars = c(-Subject, -School, - First, -Last)) %>%
  left_join(y = growth_norms %>%
              filter(Start_Season == "Winter" & End_Season == "Spring") %>%
              select(Subject, Grade, RIT, Growth_Goal),
            by = c("Subject","Grade","Start_RIT" = "RIT")) %>%
  left_join( y = caliber_multipliers, by = "Start_SBAC") %>%
  mutate(Growth_Season = "Winter-to-Spring",
         Actual_Growth = End_RIT - Start_RIT,
         Typical_Growth = Growth_Goal,
         Target_Growth = Growth_Goal*multiplier,
         Met_Typical = ifelse( Actual_Growth >= Typical_Growth,1,0),
         Met_Target = ifelse( Actual_Growth >= Target_Growth,1,0),
         Typ_not_Target = ifelse(Met_Typical == 1 & Met_Target == 0, 1, 0)
  ) %>%
  drop_na() %>%
  group_by(Grade, Subject) %>%
  mutate(n_tested = sum(n())) %>%
  filter(n_tested >= 15)


# Generate a Fall to Spring Growth data frame
# Same as above but filter Season == Fall or Spring

F_to_S_growth <- combo_map %>%
  filter(Season == "Fall" | Season == "Spring") %>%
  unite(temp, 4:9, sep = "/") %>%
  unite(scores, c(RIT, NPR, SBAC, Quartile), sep = "/") %>%
  select(-Year, -n_tested) %>%
  spread(key = Season, value = scores) %>%
  separate(Fall, c("Start_RIT", "Start_NPR", "Start_SBAC", "Start_Quartile"), sep = "/") %>%
  separate(Spring, c("End_RIT", "End_NPR", "End_SBAC", "End_Quartile"), sep = "/") %>%
  separate(temp, c("Subject", "School", "Grade", "ID", "First", "Last"), sep = "/") %>%
  mutate_each(funs(as.numeric), vars = c(-Subject, -School, - First, -Last)) %>%
  left_join(y = growth_norms %>%
              filter(Start_Season == "Fall" & End_Season == "Spring") %>%
              select(Subject, Grade, RIT, Growth_Goal),
            by = c("Subject","Grade","Start_RIT" = "RIT")) %>%
  left_join( y = caliber_multipliers, by = "Start_SBAC") %>%
  mutate(Growth_Season = "Fall-to-Spring",
         Actual_Growth = End_RIT - Start_RIT,
         Typical_Growth = Growth_Goal,
         Target_Growth = Growth_Goal*multiplier,
         Met_Typical = ifelse( Actual_Growth >= Typical_Growth,1,0),
         Met_Target = ifelse( Actual_Growth >= Target_Growth,1,0),
         Typ_not_Target = ifelse(Met_Typical == 1 & Met_Target == 0, 1, 0)
  ) %>%
  drop_na() %>%
  group_by(Grade, Subject) %>%
  mutate(n_tested = sum(n())) %>%
  filter(n_tested >= 15)

# Combine three dataframes into one growth dataframe
# You can always filter by growth season later

combo_growth <- rbind(F_to_W_growth, W_to_S_growth) %>%
  rbind(F_to_S_growth)


#### ROLLUP ####

# Load in the rCharts package for graphing

library(rCharts)
library(googleVis)


# "SBAC by Grade" page: Sankey chart of 
rollup_growth_sbac_sankey <-
  combo_growth %>%
    filter(Grade <= 8) %>%
    group_by(Subject, School, Grade, Growth_Season, Start_SBAC, End_SBAC) %>%
    summarise(Total = n()) %>%
    group_by(Subject, School, Grade, Growth_Season) %>%
    mutate(cumtotal = sum(Total),
           rank = Start_SBAC + End_SBAC) %>%
    ungroup() %>%   
    filter(cumtotal >= 15) %>%
    mutate(Start_SBAC = paste0("SBAC", as.character(Start_SBAC), " Start"),
           End_SBAC = paste0("Q", as.character(End_SBAC), " End")) %>%
    arrange(desc(rank), desc(Start_SBAC), desc(End_SBAC))

sbac_sankey <- rollup_growth_sbac_sankey %>%
  filter(Grade == "4") %>%
  arrange(School, desc(Start_SBAC), desc(End_SBAC), Growth_Season, Grade, Subject) %>%        
  select(Start_SBAC, End_SBAC, Total)

gvisSankey(sbac_sankey, from = "Start_SBAC", to = "End_SBAC", weight = "Total",
           options = list(height=400, width=600,
                          sankey="{
                          link: {
                          colorMode: 'gradient',
                          colors: ['#255694','#60A2D7','#CFCCC1','#8D8685']
                          }, 
                          node: {
                          label: {
                          fontSize: 24,
                          color: '#000',
                          bold: true,
                          italic: false
                          },
                          interactivity: true, // Allows you to select nodes.
                          labelPadding: 6,     // Horizontal distance between the label and the node.
                          nodePadding: 10,     // Vertical distance between nodes.
                          width: 20,            // Thickness of the node.
                          colors: ['#255694','#60A2D7','#CFCCC1','#8D8685']
                          }
                          }"
                )
           )

```

